name: hep-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.8
  - conda:
    - pytorch==2.4.1
    - torchvision==0.19.1
    - pytorch::torchaudio==2.4.1
    # - root # install if needed (huge package)
  - pythia8=8.312
  - pip
  - pip:
    - pandas==2.2.3
    - scikit-learn==1.6.0
    - numpy==2.2.1
    - uproot==5.5.1
    - awkward==2.7.2
    - matplotlib==3.9.3 
    - seaborn==0.13.2
    - statsmodels==0.14.4
    - tqdm==4.64.1
    - scipy==1.14.1
    - shap==0.35.0 # this is not the latest, but the one that works
    - pickleshare==0.7.5
    - plotly==5.24.1
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - matplotlib-inline
    - notebook
    - iminuit==2.30.1
    - pytest==8.3.4
    - oct2py==5.2.0
    - octave-kernel==0.32.0
    - sympy==1.13.3
    - fastjet==3.4.2.1
    - imbalanced-learn==0.12.2



### PREVIOUS CONFIG
#name: geometric
#channels:
#  - conda-forge
#  - defaults
#  - pytorch
#dependencies:
#  - python=3.8.11
#  - conda: 
#    - pytorch
#    - torchvision
#    - torchaudio
#    - cudatoolkit # =11.2
#    # - root # install if needed (huge package)
#  - pip
#  - pip:
#    - awkward==1.5.1
#    - jupyter==1.0.0
#    - jupyter-client==7.3.1
#    - jupyter-console==6.4.3
#    - jupyter-core==4.10.0
#    - jupyterlab-pygments==0.2.2
#    - jupyterlab-widgets==1.1.0
#    - matplotlib-inline==0.1.3
#    - notebook==6.4.11
#    - pandas
#    - pickleshare==0.7.5
#    - plotly==5.3.1
#    - scikit-learn
#    - scipy
#    - seaborn
#    - tqdm
#    - uproot
#    - numpy
#    - matplotlib


# more packages needed for using other frameworks
 # - pip:
  #  - -r req.txt
  #- keras==2.6.0
  #- tensorflow==2.6.0

# pytorch installation support
# https://pytorch.org/get-started/locally/

# conda root support
# https://anaconda.org/conda-forge/root/
